# Kubernetes control node
k8s_host: control_node_hostname
k8s_user: your_username

# ssh key path
ssh_key_path: ~/.ssh/id_rsa # Replace with ssh key path

# Directory where data files are stored
data_dir: data

# Flag to enable/disable qualitative evaluation (makes LLM calls)
qualitative_eval: false

# Flag to enable/disable printing the session
print_session: false
