apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-search
  namespace: default
spec:
  action: pod-failure
  mode: one
  duration: '15s'
  selector:
    labelSelectors:
      'io.kompose.service': 'rate'
      # 'io.kompose.service': 'geo'
      # 'io.kompose.service': 'mongodb-rate'
      # 'io.kompose.service': 'search'
